<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.morpheus.cloud</groupId>
        <artifactId>coding</artifactId>
        <version>0.0.1</version>
    </parent>

    <artifactId>coding-footstone</artifactId>
    <packaging>pom</packaging>

    <description> 公共模块 </description>


    <modules>
        <module>coding-footstone-core</module>
        <module>coding-footstone-seata</module>
        <module>coding-footstone-security</module>
        <module>coding-footstone-sensitive</module>
        <module>coding-footstone-swagger</module>
        <module>coding-footstone-datasource</module>
        <module>coding-footstone-notice</module>
    </modules>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>



</project>